### ISSUE TITLE
Folyószövegek betűtípusának megválasztása

### ISSUE THREAD

**Issue by kripod** [simonyiszk/frt-web#10]
Lehetőségek:

- Használjuk a megjelenítési platform alapértelmezett natív sans serif fontját, így a folyószövegeknek elvész a branding jellege, azonban gyorsabban tölt be az oldal
- Használjuk a [Raleway][] fontot, amely nincs benne az FRT arculati kézikönyvében
- Használjuk a [Rajdhani][] fontot, mellyel kevésbé lennének olvashatók a folyószövegek

[Raleway]: https://fonts.google.com/specimen/Raleway
[Rajdhani]: https://fonts.google.com/specimen/Rajdhani

**Comment by kripod** [comment]
Én az első két megoldást támogatnám, azok közül is inkább a Raleway használatát. Szerintem illik a címekben használatos Rajdhanihoz.

**Comment by adamlobler** [comment]
Raleway a legjobb a három közül szerintem is, ha nincs megkötve hogy a Rajdhanit használjuk akkor én arra szavazok.

**Comment by nonora** [comment]
Akkor használjuk a Raleway fontot a folyószöveghez.

**Comment by kripod** [comment]
Rendben, ez akkor eldőlt 😊
